### PR TITLE
Add archive output to appraise

### PR DESCRIPTION
**Pull request by AroneyS**
- [x] Implement in Appraiser
- [x] Add `-p [style output]` argument to appraise with options `standard` (default) and `archive`
  - [ ] Make `output_found_in` another style since it's incompatible with `archive`

### CODE REVIEW

**Comment by AroneyS** [comment]
@wwood The current commit gives me an archive otu table with fields `["gene", "sample", "sequence", "num_hits", "coverage", "taxonomy"]`, rather than the full fields `["gene", "sample", "sequence", "num_hits", "coverage", "taxonomy", "read_names", "nucleotides_aligned", "taxonomy_by_known?"]`.

Also, how do you want to handle the "style output" argument names. I've used "standard" and "archive" so far, but I guess you want them softcoded in a variable somewhere?

**Comment by wwood** [comment]
what current commit sorry? I'm not really following

**Comment by AroneyS** [comment]
I mean in the second commit in this pull request

**Comment by AroneyS** [comment]
@wwood ready for review

**Pull request merged**
