### PR TITLE
Appraise using query

### PR DESCRIPTION
**Pull request by AroneyS**
almost deleted due to force push
See: https://github.com/wwood/singlem/tree/c7b4f5222fc94038802adfc2d91b9ebbd288b3ec

### CODE REVIEW

**Comment by wwood** [comment]
```
(singlem-dev)cl5n007:20220927:~/git/singlem$ bin/singlem appraise --metagenome-otu-tables ~/m/share/for_sam/from_ben/mg.csv --genome-otu-tables ~/m/share/for_sam/from_ben/genome.csv 
09/27/2022 04:21:32 PM INFO: SingleM v0.13.2
...
sample  num_binned      num_not_found   percent_binned
GCA_000759375.2_ASM75937v2_genomic.fna.gz.1     410     108     79.2
total   410     108     79.2
average 410.0   108.0   79.2
```
That's a genome and then reads simulated from it as a metagenome. 

Why is that so low? I think there's 4 genes not picked up when scanning the genome (somewhat oddly) and 2 genes not picked up from the reads. That's a separate issue maybe, but since there are 26 that match between them, and 4 that are in the metag but not the genome, that should make 87% or so appraise result, not 79.2% as reported, I think?

Any ideas?

**Comment by AroneyS** [comment]
The 79% is just 410 / (410 + 108). Could it just be due to the noise from read simulation? So in this simulation, there happened to be more of the 4 genes missing from the genome than average.

**Comment by wwood** [comment]
Hmm, but counting num_hits so doing this the way you mean, and just doing a straight join on the sequence strings

446 are in the genome
72 are not in the genome

You can see details of what I did in a.ipynb in that share dir

Ideas?

**Comment by AroneyS** [comment]
Oh I think the double-counting bug was added here. Limit per sequence is set to None, so duplicate entries in the database (with identical sequences) are counted twice.
What happens if you run appraise with commit 199c66195f5335ce364117f0375f74f560453f9d ([fix num_found count bug](https://github.com/wwood/singlem/pull/104/commits/199c66195f5335ce364117f0375f74f560453f9d))?

**Comment by AroneyS** [comment]
That bug doesn't explain what is happening here, since there are no duplicates in the genome.

**Comment by AroneyS** [comment]
This is the result running on the other branch (https://github.com/wwood/singlem/pull/104).

```
sample  domain  num_binned      num_not_found   percent_binned
GCA_000759375.2_ASM75937v2_genomic.fna.gz.1     d__Archaea      0       0       0.0
GCA_000759375.2_ASM75937v2_genomic.fna.gz.1     d__Bacteria     11      0       100.0
total   d__Archaea      0       0       0.0
average d__Archaea      0.0     0.0     nan
total   d__Bacteria     11      0       100.0
average d__Bacteria     11.0    0.0     100.0
```

**Comment by AroneyS** [comment]
Found it.
Marker genes from genome: 25 (expected 26) - S3.16.SRP_SPB is duplicated in the genome, so it removed from the appraisal.
The S3.16.SRP_SPB hits in the metagenome sum to 36, so move 36 from the 446 found to the 72 not-found and you get 410 found and 108 not-found.

**Comment by wwood** [comment]
Thanks.

**Pull request merged**
